import requests

headers = {
    "Authorization": "Bearer eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzgwNzYyNjU4LCJqdGkiOiI4MjVmYzcxOS03ZDIzLTQwZmUtOGM5MC1mMDlkYzMyMWNhNzQiLCJ1c2VyX3V1aWQiOiIzODgzMWY5MS00NTZjLTQzZjAtOWQ2MS05Njc4YWM4ZTk4NjMiLCJzY29wZSI6ImF2YWlsYWJpbGl0eTpyZWFkIGV2ZW50X3R5cGVzOnJlYWQgc2NoZWR1bGVkX2V2ZW50czpyZWFkIHNjaGVkdWxpbmdfbGlua3M6d3JpdGUgdXNlcnM6cmVhZCB3ZWJob29rczpyZWFkIHdlYmhvb2tzOndyaXRlIn0.ejcri7QhHJphGO50ewmuY6qd8jnFQ0z8QnmhdILR8sMKjVQf65MGsEVJpFoCAPHp-_UUN66HGuDaaohb0R0O0A"
}

r = requests.get(
    "https://api.calendly.com/users/me",
    headers=headers
)

print(r.status_code)
print(r.json())